In [1]:
# 1. Load data
import pandas as pd
from os import listdir, getcwd

In [2]:

gdelt = pd.read_csv('gdelt_dataframe.csv')

gdelt.head()

,Actor2Geo_CountryCode,Year,GoldsteinScale,AvgTone,QuadClass,NumMentions
0,AA,2006,0.000000,4.547804,1.000000,4.000000
1,AA,2014,3.866667,0.165841,1.333333,9.333333
2,AA,2015,0.400000,-5.541607,1.500000,7.500000
3,AA,2018,-4.200000,-8.310443,3.600000,9.200000
4,AA,2019,2.400000,1.240730,1.000000,5.333333

In [3]:
# (b) Read in asylum seekers
seekers = pd.read_csv(getcwd() + '/Target_Variable/Asylum_seekers_per_country_per_year_w_prev_year.csv')
seekers = seekers.drop('Unnamed: 0', axis = 1)
seekers.head()

FileNotFoundError: [Errno 2] File b'/Users/gmholden/workspace/dsga1001/term_project/Target_Variable/Asylum_seekers_per_country_per_year_w_prev_year.csv' does not exist: b'/Users/gmholden/workspace/dsga1001/term_project/Target_Variable/Asylum_seekers_per_country_per_year_w_prev_year.csv'

In [73]:
# (c) Read in populations
pop = pd.read_csv(getcwd() + '/initial_analysis/populations.csv', skiprows = [i for i in range(0, 3)])
pop.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 63
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,...,101669.0,102046.0,102560.0,103159.0,103774.0,104341.0,104872.0,105366.0,105845.0,NaN
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996973.0,9169410.0,9351441.0,9543205.0,9744781.0,9956320.0,...,29185507.0,30117413.0,31161376.0,32269589.0,33370794.0,34413603.0,35383128.0,36296400.0,37172386.0,NaN
2,Angola,AGO,"Population, total",SP.POP.TOTL,5454933.0,5531472.0,5608539.0,5679458.0,5735044.0,5770570.0,...,23356246.0,24220661.0,25107931.0,26015780.0,26941779.0,27884381.0,28842484.0,29816748.0,30809762.0,NaN
3,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,NaN
4,Andorra,AND,"Population, total",SP.POP.TOTL,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,...,84449.0,83747.0,82427.0,80774.0,79213.0,78011.0,77297.0,77001.0,77006.0,NaN

In [77]:
# (d) Read in ISO codes
iso = pd.read_csv(getcwd() + '/Target_Variable/ISO_codes.csv')
iso.head()

,English short name,French short name,Alpha-2 code,Alpha-3 code,Numeric
0,Afghanistan,Afghanistan (l'),AF,AFG,4
1,Albania,Albanie (l'),AL,ALB,8
2,Algeria,Algérie (l'),DZ,DZA,12
3,American Samoa,Samoa américaines (les),AS,ASM,16
4,Andorra,Andorre (l'),AD,AND,20

In [99]:
# 2. Merge
# (a) seekers with iso
seekers_iso = seekers.merge(iso, left_on = 'Origin', right_on = 'English short name', validate = 'many_to_one', indicator = True)

print("Check seekers-iso merge:")
print(seekers_iso._merge.value_counts())

seekers_iso = seekers_iso.drop('_merge', axis = 1)

Check seekers-iso merge:
both          3141
right_only       0
left_only        0
Name: _merge, dtype: int64

In [100]:
# (b) merge seekers_iso with pop
seekers_iso_pop = seekers_iso.merge(pop, left_on = 'Alpha-3 code', right_on = 'Country Code', validate = 'many_to_one', indicator = True)

print("Check seekers-iso-pop merge:")
print(seekers_iso_pop._merge.value_counts())

seekers_iso_pop = seekers_iso_pop.drop('_merge', axis = 1)

Check seekers-iso-pop merge:
both          3102
right_only       0
left_only        0
Name: _merge, dtype: int64

In [103]:
# (b) merge seekers_iso_pop with gdelt
seekers_iso_pop.columns
seekers_iso_pop_gdelt = seekers_iso.merge(gdelt, left_on = 'Alpha-2 code', right_on = 'Actor2Geo_CountryCode', validate = 'many_to_many', indicator = True)

print("Check seekers-iso-pop-gdelt merge:")
print(seekers_iso_pop_gdelt._merge.value_counts())

seekers_iso_pop_gdelt = seekers_iso_pop_gdelt.drop('_merge', axis = 1)

Check seekers-iso-pop-gdelt merge:
both          1276699
right_only          0
left_only           0
Name: _merge, dtype: int64

In [ ]:
# 3. Export
seekers_iso_pop_gdelt.to_csv("merged_seekers_iso_pop_gdelt.csv")